#!/bin/sh

set -e

if [ -f "${BUILD_CONFIG:=./build.conf}" ]; then . "$BUILD_CONFIG"; fi

MODULES="${MODULES:?Build modules not defined in environment or $BUILD_CONFIG}"
readonly MODULES

case "${BUILD_SOURCE_DIR:=src}" in
(/*) ;; (*) BUILD_SOURCE_DIR="$(dirname "$BUILD_CONFIG")/$BUILD_SOURCE_DIR";;
esac

case "${BUILD_INCLUDE_DIR:=include}" in
(/*) ;; (*) BUILD_INCLUDE_DIR="$(dirname "$BUILD_CONFIG")/$BUILD_INCLUDE_DIR";;
esac

TARGET_NAME="${TARGET_NAME:-target}"
readonly TARGET_TEMP_DIR="${TARGET_TEMP_DIR:-$TARGET_NAME/tmp}"
readonly BUILD_SOURCE_DIR BUILD_INCLUDE_DIR TARGET_NAME

# General directories
readonly TARGET_LIBRARY_DIR="$TARGET_NAME/lib"
readonly TARGET_DEPEND_DIR="$TARGET_NAME/dep"
readonly TARGET_BINARY_DIR="$TARGET_NAME/bin"

# Module specific test binaries
readonly TARGET_TEST_BINARY_DIR="$TARGET_NAME/test"

# Generated sources
readonly TARGET_SOURCE_DIR="$TARGET_NAME/src"
readonly TARGET_INCLUDE_DIR="$TARGET_NAME/include"

# module definition API
BINARY() { BINNAME="${1:-$MODULE}"; }
SOURCE() { SOURCES="$SOURCES $@"; }
HEADER() { HEADERS="$HEADERS $@"; }
LINKER() { LIBRARIES="$LIBRARIES $@"; }
TEST() { TESTS="$TESTS $@"; }
REQUIRE() { REQUIREMENTS="$REQUIREMENTS $@"; }
OBJECT()
{
  MEMBER="${1%.o}"
  MEMBER_SOURCE="$MODULE_DIR/$2"
  shift 2
  OBJECTS="$OBJECTS $MEMBER.o"

  build_cc_target "$LIBRARY($MEMBER.o)" "$MEMBER_SOURCE"
  build_object_recipe "$MODULE_TEMP_DIR/$MEMBER.o" "$DEPEND" \
    "$MODULE_TEMP_DIR/$MEMBER.o" "$MEMBER_SOURCE" "$@"
  build_ar_recipe "$LIBRARY" "$MODULE_TEMP_DIR/$MEMBER.o"
  build_rm_recipe "$MODULE_TEMP_DIR/$MEMBER.o"
}

# Makefile rule generation
build_sh_recipe()
{
  printf '\t%s\n' "$*"
}

build_rm_recipe()
{
  printf '\trm -f %s\n' "$*"
}

build_cc_recipe()
{
  printf '\t$(CC) $(CFLAGS) $(CPPFLAGS) -I"%s" -I"%s" %s\n' \
    "$TARGET_INCLUDE_DIR" "$BUILD_INCLUDE_DIR" "$*"
}

# Invoke the compiler with paths and module linkage included
build_end_target()
{
  echo
}

build_ld_recipe()
{
  printf "\t\
\$(CC) \$(CFLAGS) \$(LDFLAGS) \
-L$TARGET_LIBRARY_DIR %s \
\$(MODULE_LDFLAGS.$MODULE)\n" \
    "$*"
}

# 1: Makefile target name, 2: Output file
build_depend_flags()
{
  echo -MMD -MP -MT "\"$1"\" -MF "\"$2"\"
}

build_source_target()
{
  TARGET_=$1
  shift
  printf '%s: %s\n' "$GENERATED_SOURCE_DIR/$TARGET_" "$*"
}

build_include_target()
{
  TARGET_=$1
  shift
  printf '%s: %s\n' "$TARGET_INCLUDE_DIR/$TARGET_" "$*"
}

build_cc_target()
{
  TARGET_=$1
  shift
  printf '%s: %s $(MODULE_HEADERS.%s)\n' "$TARGET_" "$*" "$MODULE"
}

build_ld_target()
{
  TARGET_=$1
  shift
  printf '%s: %s $(MODULE_LINK.%s)\n' "$TARGET_" "$*" "$MODULE"
}

build_bin_target()
{
  TARGET_=$1
  shift
  printf '%s: %s $(MODULE_LINK.%s) $(MODULE_HEADERS.%s)\n' \
    "$TARGET_" "$*" "$MODULE" "$MODULE"
}

# <archive> <member>
build_ar_recipe()
{
  printf '\t$(AR) -rc "%s" "%s"\n' "$1" "$2"
}

# <target> <archive> <object> <source> [<extra cc args>...]
build_object_recipe()
{
  TARGET_="$1"
  ARCHIVE_="$2"
  OBJECT_="$3"
  MKFILE_="${OBJECT_%.o}.d"
  SOURCE_="$4"
  shift 4

  build_cc_recipe "$@" \
    $(build_depend_flags "$TARGET_" "$MKFILE_") \
    -c "\"$SOURCE_"\" \
    -o "\"$OBJECT_"\"

  build_ar_recipe "$ARCHIVE_" "$MKFILE_"
  build_rm_recipe "$MKFILE_"
}

# target/lib/libfoo.a: target/lib/libfoo.a(bar.o baz.o)
#         $(AR) -s target/lib/libfoo.a
build_lib_target() {
  printf '%s: %s( ' "$LIBRARY" "$LIBRARY"
  printf '\\\n\t%s ' $OBJECTS
  printf ')\n\t$(AR) -s "%s"\n\n' "$LIBRARY"
}

build_module_bin_target() {
  printf '%s: %s\n\n' "$MODULE" "$TARGET_BINARY_DIR/$BINNAME"

  if [ "$BINNAME" != "$MODULE" ]; then
    printf '%s: %s\n' "$BINNAME" "$TARGET_BINARY_DIR/$BINNAME"
    printf '.PHONY: %s\n' "$BINNAME"
  fi

  build_ld_target "$TARGET_BINARY_DIR/$BINNAME" "$LIBRARY"
  build_ld_recipe "$LIBRARY" -o "\"$TARGET_BINARY_DIR/$BINNAME\""
  build_end_target
}

build_module_target() {
  printf '%s: %s\n\n' "$MODULE" "$LIBRARY"
  printf '%s: %s\n\n' "lib$MODULE.a" "$LIBRARY"
  printf '.PHONY: %s %s\n\n' "$MODULE" "lib$MODULE.a"
  printf 'all: %s\n\n' "$MODULE"

  build_lib_target
  if [ -n "$BINNAME" ]; then build_module_bin_target; fi
}

build_mkdir() { if [ ! -d "$1" ]; then mkdir "$1"; fi; }

build_directories() {
  build_mkdir "$TARGET_NAME"
  build_mkdir "$TARGET_TEMP_DIR"
  build_mkdir "$TARGET_LIBRARY_DIR"
  build_mkdir "$TARGET_DEPEND_DIR"
  build_mkdir "$TARGET_BINARY_DIR"

  build_mkdir "$TARGET_TEST_BINARY_DIR"
  build_mkdir "$TARGET_SOURCE_DIR"
  build_mkdir "$TARGET_INCLUDE_DIR"

  for MODULE in $MODULES; do
    # For object and dependency files
    build_mkdir "$TARGET_TEMP_DIR/$MODULE"

    # For test object and dependency files
    build_mkdir "$TARGET_TEMP_DIR/$MODULE/test"

    # Test binaries
    build_mkdir "$TARGET_TEST_BINARY_DIR/$MODULE"

    # Generated files
    build_mkdir "$TARGET_SOURCE_DIR/$MODULE"
    build_mkdir "$TARGET_INCLUDE_DIR/$MODULE"
  done
}

build_prelude() {
  # Prelude rules
  printf '.POSIX:\n.SUFFIXES:\n'
  printf 'all:\nclean: clean-dep clean-lib clean-bin\n'
  printf 'clean-dep: ; rm -f %s/*\n' "${TARGET_DEPEND_DIR:?}"
  printf 'clean-lib: ; rm -f %s/*\n' "${TARGET_LIBRARY_DIR:?}"
  printf 'clean-bin: ; rm -f %s/*\n\n' "${TARGET_BINARY_DIR:?}"
  printf '.PHONY: all clean clean-dep clean-lib clean-bin\n\n'
}

build_postlude() {
  printf 'list-tests:\n\tfor T in'
  for M in $MODULES; do printf ' $(MODULE_TESTS.%s)' "$M"; done
  printf '; do echo $$T; done\n'
}

build_module_variables() {
  printf 'MODULE_LINK.%s =' "$MODULE"
  for R in $REQUIREMENTS; do
    printf ' %s/lib%s.a $(MODULE_LINK.%s)' "$TARGET_LIBRARY_DIR" "$R" "$R"
  done

  printf '\nMODULE_LDFLAGS.%s = %s' "$MODULE" "$LIBRARIES"
  if [ "$REQUIREMENTS" ]; then
    printf ' -l%s' $REQUIREMENTS
    printf ' $(MODULE_LDFLAGS.%s)' $REQUIREMENTS
  fi
  printf '\n'

  printf '\nMODULE_TESTS.%s =' "$MODULE"
  printf ' %s' $TESTS
  printf '\n'

  printf '\nMODULE_HEADERS.%s =' "$MODULE"
  if [ "$HEADERS" ]; then printf " $TARGET_INCLUDE_DIR/%s" $HEADERS; fi
  if [ "$REQUIREMENTS" ]; then printf ' $(MODULE_HEADERS.%s)' $REQUIREMENTS; fi
  printf '\n'

  printf '.PHONY: %s-test\n' "$MODULE"
  printf '%s-test: $(MODULE_TESTS.%s)\n' "$MODULE" "$MODULE"
  printf 'test: %s-test\n' "$MODULE"
  printf '\n'
}

readonly BUILD_VARIABLE_RE='^MODULE_\(LINK\|LDFLAGS\|HEADERS\|TESTS\)\.[^= ]* ='
build_variable_filter() { sed -n "/${BUILD_VARIABLE_RE}/p"; }
build_rules_filter() { sed "/${BUILD_VARIABLE_RE}/d"; }

build_makefile() {
  unset BINNAME REQUIREMENTS SOURCES OBJECTS LIBRARIES TESTS HEADERS

  build_prelude

  # Produce all normal rules (each ``module'' file evaluated in independent
  # sub-shell)
  MAKEFILE=$(for MODULE in $MODULES; do (
    DEPEND="${TARGET_DEPEND_DIR:?}/m$MODULE.a"
    TEST_DEPEND="${TARGET_DEPEND_DIR:?}/t$MODULE.a"
    LIBRARY="${TARGET_LIBRARY_DIR:?}/lib$MODULE.a"
    MODULE_DIR="${BUILD_SOURCE_DIR:?}/$MODULE"
    GENERATED_SOURCE_DIR="$TARGET_SOURCE_DIR/$MODULE"
    GENERATED_INCLUDE_DIR="$TARGET_INCLUDE_DIR/$MODULE"
    MODULE_TEMP_DIR="$TARGET_TEMP_DIR/$MODULE"
    TEST_TEMP_DIR="$TARGET_TEMP_DIR/$MODULE/test"
    TEST_BIN_DIR="$TARGET_TEST_BINARY_DIR/$MODULE"
    readonly MODULE DEPEND TEST_DEPEND LIBRARY MODULE_DIR
    readonly GENERATED_SOURCE_DIR GENERATED_SOURCE_DIR
    readonly TEST_TEMP_DIR TEST_BIN_DIR

    cd "$MODULE_DIR"
    if [ -f module ]; then . ./module; fi

    build_module_variables

    if [ -z "$SOURCES" -a -z "$OBJECTS" ]; then SOURCES=*.c; fi
    for MEMBER_SOURCE in $SOURCES; do
      OBJECT "${MEMBER_SOURCE%.c}.o" "$MEMBER_SOURCE"
    done

    build_module_target
  ) || exit 1; done)

  # Put variable definitions first and rules second
  echo "$MAKEFILE" | build_variable_filter
  echo
  echo "$MAKEFILE" | build_rules_filter

  build_postlude

  # Include recursive file dependencies
  if [ -d "$TARGET_DEPEND_DIR" ]; then
    find "$TARGET_DEPEND_DIR" -name '*.a' -exec "${AR:-ar}" -p {} \;
  fi
}

build_main() {
  build_directories
  build_makefile | ${MAKE:-make -rf-} "$@"
}

build_main "$@"
