#!/bin/sh

set -e

dir="$(pwd)"

fixture() {
  if [ "$1" == "-c" ]; then
    # Copy fixture (e.g. for changing sources, testing normal build)
    cp -r "$dir/fixtures/$2/"* .
    unset BUILD_CONFIG
  else
    # Use sources in non-current directory
    export BUILD_CONFIG="$dir/fixtures/$1/build.conf"
  fi
}

build() {
  $dir/build $@
}

build_or_fail() {
  build $@ || fail "Unable to build: $@"
}

fail() {
  if [ $# -gt 0 ]; then echo "$@" >&2; fi
  exit 1
}

library_must_contain() { # library member symbol [type=T]
  if [ -z "$(nm -PA "$1" | grep "^$1\[$2\]: $3 ${4:-T}")" ]; then
    echo "$3 not found in $1[$2]" >&2
    test -e "$1" && nm -PA $1 >&2
    fail
  fi
}

strings_must_equal() { # [message] received expected
  if [ $# -eq 3 ]; then
    [ "$2" = "$3" ] || fail "$1: got [$2], expected [$3]"
  else
    [ "$1" = "$2" ] || fail "got [$1], expected [$2]"
  fi
}

file_must_exist() { # file
  [ -e "$1" ] || fail "Not found: $1"
}

directory_must_exist() { # file
  [ -d "$1" ] || fail "Not found: $1"
}

generate_rules() {
  unset err
  if build -s; then
    echo "# Makefile"
  else
    echo "# Broken Makefile"
    err=1
  fi
  build Makefile
  exit $err
}

TESTS="$(cd tests; find ${@:-.} -type f -print | sort | uniq | sed 's/^.\///')"
echo 1..$(echo "$TESTS" | wc -l)

# Run tests specified on command line
for t in $TESTS; do
  DIR=$(mktemp -d);
  mkdir -p $(dirname logs/$t)
  {
    time {
      if (cd $DIR; . "$dir/tests/$t";) 1>"logs/$t" 2>&1; then
        echo ok $t
      else
        echo "not ok $t"
      fi
    }
  } 2>&1 | awk '/ok/ { print } !/ok/ && /./ { printf("\t%s\n", $0) }'
  rm -r $DIR
done
